version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /ci-cd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /ci-cd/docker-credentials/password
    DOCKER_REGISTRY_URL: /ci-cd/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r simple-python-app/requirements.txt
  build:
    commands:
      - cd simple-python-app
      - echo "Building Docker image"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-app:latest"
      - cd ..
      - mkdir -p build_output
      - cp -r appspec.yml scripts simple-python-app build_output/  # Ensure scripts and app files are copied
  post_build:
    commands:
      - echo "Build is successful!"

artifacts:
  files:
    - '**/*'
  base-directory: build_output
